#!/usr/bin/env python3

import sys, os

# Given a filename containing a list of commonly-used passwords, one per line,
# return a list containing the passwords. NOTE: The filename must be in the
# same directory as this script.
# @param [String] filename The name of the file in this script's directory
#                 with common passwords.
# @return [List] Commonly used passwords from the file in question, in a List
def get_list_of_passwords(filename):
    ret = []

    # Get the path to the current directory and add the supplied filename
    filename = os.path.join(os.path.dirname(sys.argv[0]), filename)
    with open(filename, 'r') as f:
        for line in f.readlines():
            ret.append(line.strip())

    return ret

# Given a word and the filename of a document containing common passwords,
# check whether the word is one of the common passwords in the document.
# @param [String] word A word, supplied by a user, to be evaulated against the list
# @param [String] password_filename The name of the file in this script's directory
#                 with common passwords.
# @return [Boolean] True if the word is in the list of common passwords,
#                   False otherwise
def main(word, password_filename = '1000-most-common-passwords.txt'):
    # Get list of most commonly-used passwords
    passwords = get_list_of_passwords(password_filename)
    
    if word in passwords:
        return True
    return False

if __name__ == '__main__':
    # Ensure that the right number of args are provided
    if len(sys.argv) != 2:
        print('Usage: password_check [password]')
        sys.exit()

    result = main(sys.argv[1])
    if result:
        print('Common password')
    else:
        print('Not common password')
